id = "lprog"
name = "\\lprog"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "Zed support for the Lambda prog (\\lprog) language"
repository = "https://github.com/Gaspartcho/zed-lprog"


[grammars.lprog]
repository = "https://github.com/Gaspartcho/tree-sitter-lprog"
rev = "6196255e5e86111cc8ca9c1c0d482ec4c13e61aa"
